from __future__ import annotations

from typing import Any

PRESET_VALUES: dict[str, dict[str, Any]] = {
    "Still": {
        "scale_start_percent": 100.0,
        "scale_end_percent": 100.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 0.0,
        "offset_y_end_percent": 0.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 0.0,
        "cycles": 1.0,
        "ping_pong": False,
    },
    "Zoom In": {
        "scale_start_percent": 100.0,
        "scale_end_percent": 118.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 0.0,
        "offset_y_end_percent": 0.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 4.0,
        "cycles": 1.0,
        "ping_pong": False,
    },
    "Zoom Out": {
        "scale_start_percent": 120.0,
        "scale_end_percent": 100.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 0.0,
        "offset_y_end_percent": 0.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 4.0,
        "cycles": 1.0,
        "ping_pong": False,
    },
    "Rotate": {
        "scale_start_percent": 100.0,
        "scale_end_percent": 100.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 360.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 0.0,
        "offset_y_end_percent": 0.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 4.0,
        "cycles": 1.0,
        "ping_pong": False,
    },
    "Pan Left to Right": {
        "scale_start_percent": 112.0,
        "scale_end_percent": 112.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": -12.0,
        "offset_x_end_percent": 12.0,
        "offset_y_start_percent": 0.0,
        "offset_y_end_percent": 0.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 4.0,
        "cycles": 1.0,
        "ping_pong": True,
    },
    "Pan Bottom to Top": {
        "scale_start_percent": 112.0,
        "scale_end_percent": 112.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 12.0,
        "offset_y_end_percent": -12.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 4.0,
        "cycles": 1.0,
        "ping_pong": True,
    },
    "Pulse": {
        "scale_start_percent": 100.0,
        "scale_end_percent": 100.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 0.0,
        "offset_y_end_percent": 0.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 7.0,
        "cycles": 2.0,
        "ping_pong": False,
    },
    "Bounce": {
        "scale_start_percent": 100.0,
        "scale_end_percent": 100.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 7.0,
        "offset_y_end_percent": 7.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 14.0,
        "cycles": 2.0,
        "ping_pong": False,
    },
    "Shake": {
        "scale_start_percent": 103.0,
        "scale_end_percent": 103.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 0.0,
        "offset_y_end_percent": 0.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 3.0,
        "cycles": 8.0,
        "ping_pong": False,
    },
    "Fade In": {
        "scale_start_percent": 100.0,
        "scale_end_percent": 100.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 0.0,
        "offset_y_end_percent": 0.0,
        "opacity_start_percent": 0.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 0.0,
        "cycles": 1.0,
        "ping_pong": False,
    },
    "Ken Burns": {
        "scale_start_percent": 102.0,
        "scale_end_percent": 125.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": -7.0,
        "offset_x_end_percent": 7.0,
        "offset_y_start_percent": 4.0,
        "offset_y_end_percent": -4.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 4.0,
        "cycles": 1.0,
        "ping_pong": True,
    },
    "Spin & Zoom": {
        "scale_start_percent": 85.0,
        "scale_end_percent": 120.0,
        "rotation_start_degrees": -18.0,
        "rotation_end_degrees": 18.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 0.0,
        "offset_y_end_percent": 0.0,
        "opacity_start_percent": 35.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 4.0,
        "cycles": 1.0,
        "ping_pong": True,
    },
    "Orbit": {
        "scale_start_percent": 104.0,
        "scale_end_percent": 104.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 0.0,
        "offset_y_end_percent": 0.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 6.0,
        "cycles": 1.0,
        "ping_pong": False,
    },
    "Wobble": {
        "scale_start_percent": 104.0,
        "scale_end_percent": 104.0,
        "rotation_start_degrees": 0.0,
        "rotation_end_degrees": 0.0,
        "offset_x_start_percent": 0.0,
        "offset_x_end_percent": 0.0,
        "offset_y_start_percent": 0.0,
        "offset_y_end_percent": 0.0,
        "opacity_start_percent": 100.0,
        "opacity_end_percent": 100.0,
        "amplitude_percent": 5.0,
        "cycles": 3.0,
        "ping_pong": False,
    },
    "Custom": {},
}

PRESET_NAMES = tuple(PRESET_VALUES.keys())
